baseURL = "./"
languageCode = "en-us"
title = "Nombre Estudiante - Repositorio"
themesDir = "./"
theme = "template"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  homepage_intro = 'Documentaci贸n.'
  homepage_image = '/images/terminal.gif'

  [params.homepage_meta_tags]
    meta_description = "Documentaci贸n."
    meta_og_title = "Documentaci贸n"
    meta_og_type = "website"
    meta_og_url = "https://designlab.uai.cl/"
    meta_og_image = "https://designlab.uai.cl/assets/themes/designlab/img/logos/logo.png"
    meta_og_description = "Documentaci贸n"
    meta_twitter_card = "summary"
    meta_twitter_site = "@lab_uai"
    meta_twitter_creator = "@lab_uai"

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"
